Bookify.Web/Controllers/SubscribersController.cs
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bookify.Web.Controllers;

[Authorize(Roles = AppRoles.Reception)]
public class SubscribersController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly IDataProtector _dataProtector;
    private readonly IMapper _mapper;
    private readonly IImageService _imageService;
    public SubscribersController(ApplicationDbContext context, IDataProtectionProvider dataProtector, IMapper mapper, IImageService imageService)
    {
        _context = context;
        _dataProtector = dataProtector.CreateProtector("MySecureKey");
        _mapper = mapper;
        _imageService = imageService;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Search(SearchFormViewModel model)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        var subscriber = _context.Subscribers.SingleOrDefault(s => 
                                                s.MobileNumber == model.value ||
                                                s.NationalId == model.value ||
                                                s.Email == model.value);

        var viewModel = _mapper.Map<SubscriberSearchResultViewModel>(subscriber);

        if (subscriber is not null)
            viewModel.Key = _dataProtector.Protect(subscriber.Id.ToString());

        return PartialView("_Result", viewModel);
    }

    public IActionResult Details(string id)
    {
        var subscriberId = int.Parse(_dataProtector.Unprotect(id));
        var subscriber = _context.Subscribers
            .Include(s => s.Governorate)
            .Include(s => s.Area)
            .Include(s => s.Subscriptions)
            .SingleOrDefault(s => s.Id == subscriberId);

        if (subscriber == null)
            return NotFound();

        var viewModel = _mapper.Map<SubscriberViewModel>(subscriber);
        viewModel.Key = id;

        return View(viewModel);
    }

    public IActionResult Create()
    {
        return View("Form", PopulateViewModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(SubscriberFormViewModel model)
    {
        if (!ModelState.IsValid)
            return View("Form", PopulateViewModel());

        var subscriber = _mapper.Map<Subscriber>(model);
        var imageName = $"{Guid.NewGuid()}{Path.GetExtension(model.Image!.FileName)}";
        var imagePath = "/images/subscribers";
        var (isUploaded, errorMassage) = await _imageService.UploadAsync(model.Image, imageName, imagePath, true);

        if (!isUploaded) {
            ModelState.AddModelError("Image", errorMassage!);
            return View("Form", PopulateViewModel());
        }

        subscriber.ImageUrl = $"{imagePath}/{imageName}";
        subscriber.ImageThumbnailUrl = $"{imagePath}/thumb/{imageName}";
        subscriber.CreatedById = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;

        // Add Subscriber Subscription
        subscriber.Subscriptions.Add(new Subscription
        {
            CreatedById = subscriber.CreatedById,
            CreatedOn = subscriber.CreatedOn,
            StartDate = DateTime.Today,
            EndDate = DateTime.Today.AddYears(1)
        });

        _context.Add(subscriber);
        _context.SaveChanges();

        var subscriberId = _dataProtector.Protect(subscriber.Id.ToString());

        return RedirectToAction(nameof(Details), new { id = subscriberId });
    }

    public IActionResult Edit(string id)
    {
        var subscriberId = int.Parse(_dataProtector.Unprotect(id));
        var subscriber = _context.Subscribers.Find(subscriberId);

        if (subscriber is null)
            return NotFound();

        var model = _mapper.Map<SubscriberFormViewModel>(subscriber);
        var viewModel = PopulateViewModel(model);
        viewModel.Key = id;

        return View("Form", viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(SubscriberFormViewModel model)
    {
        if (!ModelState.IsValid)
            return View("Form", PopulateViewModel());

        var subscriberId = int.Parse(_dataProtector.Unprotect(model.Key));
        var subscriber = _context.Subscribers.Find(subscriberId);

        if (subscriber is null)
            return NotFound();

        if (model.Image is not null)
        {
            if (!string.IsNullOrEmpty(subscriber.ImageUrl))
                _imageService.Delete(subscriber.ImageUrl, subscriber.ImageThumbnailUrl);

            var imageName = $"{Guid.NewGuid()}{Path.GetExtension(model.Image.FileName)}";
            var imagePath = "/images/subscribers";
            var (isUploaded, errorMassage) = await _imageService.UploadAsync(model.Image, imageName, imagePath, true);

            if (!isUploaded)
            {
                ModelState.AddModelError("Image", errorMassage!);
                return View("Form", PopulateViewModel());
            }

            model.ImageUrl = $"{imagePath}/{imageName}";
            model.ImageThumbnailUrl = $"{imagePath}/thumb/{imageName}";
        }
        else if (!string.IsNullOrEmpty(subscriber.ImageUrl))
        {
            model.ImageUrl = subscriber.ImageUrl;
            model.ImageThumbnailUrl = subscriber.ImageThumbnailUrl;
        }

        subscriber = _mapper.Map(model, subscriber);
        subscriber.LastUpdatedById = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
        subscriber.LastUpdatedOn = DateTime.Now;

        _context.SaveChanges();

        return RedirectToAction(nameof(Details), new { id = model.Key });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult RenewSubscription(string sKey)
    {
        var subscriberId = int.Parse(_dataProtector.Unprotect(sKey));
        var subscriber = _context.Subscribers
            .Include(s => s.Subscriptions)
            .SingleOrDefault(s => s.Id == subscriberId);

        if (subscriber == null)
            return NotFound();

        if (subscriber.IsBlackListed)
            return BadRequest();

        var lastSubscription = subscriber.Subscriptions.Last();
        var startDate = lastSubscription.EndDate < DateTime.Today ? DateTime.Today : lastSubscription.EndDate.AddDays(1);
        var newSubscription = new Subscription
        {
            CreatedById = User.FindFirst(ClaimTypes.NameIdentifier)!.Value,
            CreatedOn = DateTime.Now,
            StartDate = startDate,
            EndDate = startDate.AddYears(1)
        };

        subscriber.Subscriptions.Add(newSubscription);
        _context.SaveChanges();

        var viewModel = _mapper.Map<SubscriptionViewModel>(newSubscription);

        return PartialView("_SubscriptionRow", viewModel);
    }

    [AjaxOnly]
    public IActionResult GetAreas(int governorateId)
    {
        var areas = _context.Areas
                            .Where(a => a.GovernorateId == governorateId && !a.IsDeleted)
                            .OrderBy(a => a.Name)
                            .ToList();

        return Ok(_mapper.Map<IEnumerable<SelectListItem>>(areas));
    }

    public IActionResult AllowNationalId(SubscriberFormViewModel model)
    {
        var subscriberId = string.IsNullOrEmpty(model.Key) ? 0 : int.Parse(_dataProtector.Unprotect(model.Key));
        var subscriber = _context.Subscribers.FirstOrDefault(s => s.NationalId == model.NationalId);
        var isAllowed = subscriber is null || subscriber.Id.Equals(subscriberId);

        return Json(isAllowed);
    }

    public IActionResult AllowMobileNumber(SubscriberFormViewModel model)
    {
        var subscriberId = string.IsNullOrEmpty(model.Key) ? 0 : int.Parse(_dataProtector.Unprotect(model.Key));
        var subscriber = _context.Subscribers.FirstOrDefault(s => s.MobileNumber == model.MobileNumber);
        var isAllowed = subscriber is null || subscriber.Id.Equals(subscriberId);

        return Json(isAllowed);
    }

    public IActionResult AllowEmail(SubscriberFormViewModel model)
    {
        var subscriberId = string.IsNullOrEmpty(model.Key) ? 0 : int.Parse(_dataProtector.Unprotect(model.Key));
        var subscriber = _context.Subscribers.FirstOrDefault(s => s.Email == model.Email);
        var isAllowed = subscriber is null || subscriber.Id.Equals(subscriberId);

        return Json(isAllowed);
    }

    private SubscriberFormViewModel PopulateViewModel(SubscriberFormViewModel? model = null)
    {
        SubscriberFormViewModel viewModel = model is null ? new SubscriberFormViewModel() : model;

        var governorates = _context.Governorates.Where(g => !g.IsDeleted).OrderBy(g => g.Name).ToList();
        viewModel.Governorates = _mapper.Map<IEnumerable<SelectListItem>>(governorates);

        if (model?.GovernorateId > 0)
        {
            var areas = _context.Areas
                                .Where(a => a.GovernorateId == model.GovernorateId && !a.IsDeleted)
                                .OrderBy(a => a.Name)
                                .ToList();

            viewModel.Areas = _mapper.Map<IEnumerable<SelectListItem>>(areas);
        }

        return viewModel;
    }
}

Bookify.Web/Views/Subscribers/Form.cshtml
@model SubscriberFormViewModel
@{
    ViewData["Title"] = "Subscriber Form";
}

<div class="card shadow-sm">
    <div class="card-header">
        <h3 class="card-title">@(string.IsNullOrEmpty(Model.Key) ? "Add" : "Edit") Subscriber</h3>
    </div>
    <div class="card-body">
        <form id="Form" method="post" asp-controller="Subscribers" enctype="multipart/form-data">
            @if (!string.IsNullOrEmpty(Model.Key))
            {
                <input type="hidden" asp-for="Key" />
            }
            <!--begin::Input group-->
            <div class="row mb-6">
                <!--begin::Label-->
                <label class="col-lg-4 col-form-label required fw-semibold fs-6" asp-for="Image"></label>
                <!--end::Label-->
                <!--begin::Col-->
                <div class="col-lg-8">
                    <!--begin::Image input-->
                    <div class="image-input image-input-empty" data-kt-image-input="true" style="background-image: url(@(string.IsNullOrEmpty(Model.ImageUrl) ? "/assets/images/avatar-blank.svg" : Model.ImageThumbnailUrl))">
                        <!--begin::Preview existing avatar-->
                        <div class="image-input-wrapper w-100px h-100px"></div>
                        <!--end::Preview existing avatar-->
                        <!--begin::Label-->
                        <label class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="change" data-bs-toggle="tooltip" aria-label="Change avatar" data-bs-original-title="Change avatar" data-kt-initialized="1">
                            <i class="ki-solid ki-pencil fs-7"></i>
                            <!--begin::Inputs-->
                            <input type="file" asp-for="Image" accept=".png, .jpg, .jpeg">
                            <input type="hidden" name="avatar_remove">
                            <!--end::Inputs-->
                        </label>
                        <!--end::Label-->
                        <!--begin::Cancel-->
                        <span class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="cancel" data-bs-toggle="tooltip" aria-label="Cancel avatar" data-bs-original-title="Cancel avatar" data-kt-initialized="1">
                            <i class="ki-solid ki-cross fs-2"></i>
                        </span>
                        <!--end::Cancel-->
                        <!--begin::Remove-->
                        <span class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="remove" data-bs-toggle="tooltip" aria-label="Remove avatar" data-bs-original-title="Remove avatar" data-kt-initialized="1">
                            <i class="ki-solid ki-cross fs-2"></i>
                        </span>
                        <!--end::Remove-->
                    </div>
                    <!--end::Image input-->
                    <!--begin::Hint-->
                    <div class="form-text">Allowed file types: png, jpg, jpeg and cannot be more that 2 MB.</div>
                    <span asp-validation-for="Image" class="text-danger d-block"></span>
                    <!--end::Hint-->
                </div>
                <!--end::Col-->
            </div>
            <!--end::Input group-->
            <!--begin::Input group-->
            <div class="row mb-6">
                <!--begin::Label-->
                <label class="col-lg-4 col-form-label required fw-semibold fs-6">Full Name</label>
                <!--end::Label-->
                <!--begin::Col-->
                <div class="col-lg-8">
                    <!--begin::Row-->
                    <div class="row">
                        <!--begin::Col-->
                        <div class="col-lg-6 fv-row fv-plugins-icon-container">
                            <input type="text" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0" placeholder="First name" asp-for="FirstName">
                            <div class="fv-plugins-message-container fv-plugins-message-container--enabled invalid-feedback"></div>
                            <span asp-validation-for="FirstName" class="fv-plugins-message-container invalid-feedback"></span>
                        </div>
                        <!--end::Col-->
                        <!--begin::Col-->
                        <div class="col-lg-6 fv-row fv-plugins-icon-container">
                            <input type="text" class="form-control form-control-lg form-control-solid" placeholder="Last name" asp-for="LastName">
                            <span asp-validation-for="LastName" class="fv-plugins-message-container invalid-feedback"></span>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Row-->
                </div>
                <!--end::Col-->
            </div>
            <!--end::Input group-->
            <!--begin::Input group-->
            <div class="row mb-6">
                <!--begin::Label-->
                <label class="col-lg-4 col-form-label required fw-semibold fs-6" asp-for="DateOfBirth"></label>
                <!--end::Label-->
                <!--begin::Col-->
                <div class="col-lg-8 fv-row fv-plugins-icon-container">
                    <input type="text" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0 js-datepicker" placeholder="Date of Birth" asp-for="DateOfBirth">
                    <span asp-validation-for="DateOfBirth" class="fv-plugins-message-container invalid-feedback"></span>
                </div>
                <!--end::Col-->
            </div>
            <!--end::Input group-->
            <!--begin::Input group-->
            <div class="row mb-6">
                <!--begin::Label-->
                <label class="col-lg-4 col-form-label required fw-semibold fs-6" asp-for="NationalId"></label>
                <!--end::Label-->
                <!--begin::Col-->
                <div class="col-lg-8 fv-row fv-plugins-icon-container">
                    <input type="text" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0" placeholder="National Id" asp-for="NationalId">
                    <span asp-validation-for="NationalId" class="fv-plugins-message-container invalid-feedback"></span>
                </div>
                <!--end::Col-->
            </div>
            <!--end::Input group-->
            <!--begin::Input group-->
            <div class="row mb-6">
                <!--begin::Label-->
                <label class="col-lg-4 col-form-label required fw-semibold fs-6">Contacts</label>
                <!--end::Label-->
                <!--begin::Col-->
                <div class="col-lg-8">
                    <!--begin::Row-->
                    <div class="row">
                        <!--begin::Col-->
                        <div class="col-lg-6 fv-row fv-plugins-icon-container">
                            <input type="text" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0" placeholder="Email" asp-for="Email">
                            <span asp-validation-for="Email" class="fv-plugins-message-container invalid-feedback"></span>
                        </div>
                        <!--end::Col-->
                        <!--begin::Col-->
                        <div class="col-lg-6 fv-row fv-plugins-icon-container">
                            <input type="text" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0" placeholder="Mobile Number" asp-for="MobileNumber">
                            <span asp-validation-for="MobileNumber" class="fv-plugins-message-container invalid-feedback"></span>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Row-->
                </div>
                <!--end::Col-->
            </div>
            <!--end::Input group-->
            <!--begin::Input group-->
            <div class="row mb-6">
                <!--begin::Label-->
                <label class="col-lg-4 col-form-label required fw-semibold fs-6">Governorate/Area</label>
                <!--end::Label-->
                <!--begin::Col-->
                <div class="col-lg-8">
                    <!--begin::Row-->
                    <div class="row">
                        <!--begin::Col-->
                        <div class="col-lg-6 fv-row fv-plugins-icon-container">
                            <select data-control="select2" data-placeholder="Select a governorate..." class="form-select form-select-solid form-select-lg fw-semibold" asp-for="GovernorateId" asp-items="Model.Governorates">
                                <option value="">Select a governorate...</option>
                            </select>
                            <span asp-validation-for="GovernorateId" class="fv-plugins-message-container invalid-feedback"></span>
                        </div>
                        <!--end::Col-->
                        <!--begin::Col-->
                        <div class="col-lg-6 fv-row fv-plugins-icon-container">
                            <select data-control="select2" data-placeholder="Select a area..." class="form-select form-select-solid form-select-lg fw-semibold" asp-for="AreaId" asp-items="Model.Areas">
                                <option value="">Select a area...</option>
                            </select>
                            <span asp-validation-for="AreaId" class="fv-plugins-message-container invalid-feedback"></span>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Row-->
                </div>
                <!--end::Col-->
            </div>
            <!--end::Input group-->
            <!--begin::Input group-->
            <div class="row mb-6">
                <!--begin::Label-->
                <label class="col-lg-4 col-form-label required fw-semibold fs-6" asp-for="Address"></label>
                <!--end::Label-->
                <!--begin::Col-->
                <div class="col-lg-8 fv-row fv-plugins-icon-container">
                    <textarea class="form-control form-control-lg form-control-solid mb-3 mb-lg-0" placeholder="Address" asp-for="Address"></textarea>
                    <span asp-validation-for="Address" class="fv-plugins-message-container invalid-feedback"></span>
                </div>
                <!--end::Col-->
            </div>
            <!--end::Input group-->
            <!--begin::Input group-->
            <div class="row mb-6">
                <!--begin::Label-->
                <label class="col-lg-4 col-form-label fw-semibold fs-6">Has WhatsApp?</label>
                <!--end::Label-->
                <!--begin::Col-->
                <div class="col-lg-8 pt-3">
                    <!--begin::Row-->
                    <div class="row">
                        <!--begin::Col-->
                        <div class="col-lg-3 fv-row fv-plugins-icon-container align-self-center">
                            <label class="form-check form-check-custom form-check-inline form-check-solid me-5">
                                <input class="form-check-input" type="checkbox" asp-for="HasWhatsApp">
                                <span class="fw-semibold ps-2 fs-6">Yes</span>
                            </label>
                            <span asp-validation-for="HasWhatsApp" class="fv-plugins-message-container invalid-feedback"></span>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Row-->
                </div>
                <!--end::Col-->
            </div>
            <!--end::Input group-->
        </form>
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary" form="Form">
            <span class="indicator-label">
                Save
            </span>
            <span class="indicator-progress">
                Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
            </span>
        </button>
        <a class="btn btn-light text-primary ms-3" asp-action="Index">Cancel</a>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/SubscriberForm.js" asp-append-version="true"></script>
}

Bookify.Web/Views/Subscribers/Index.cshtml
@model SearchFormViewModel
@{
	ViewData["Title"] = "Subscribers";
}

<!--begin::Form-->
<form asp-action="Search"
	  data-ajax="true"
	  data-ajax-method="post"
	  data-ajax-begin="disableSubmitButton"
	  data-ajax-update="#Result"
	  data-ajax-failure="showErrorMessage"
	  data-ajax-complete="onModalComplete">
	<!--begin::Card-->
	<div class="card mb-7">
		<div class="card-header">
			<h3 class="card-title">Find Subscriber</h3>
		</div>
		<!--begin::Card body-->
		<div class="card-body">
			<!--begin::Compact form-->
			<div class="d-flex align-items-center">
				<!--begin::Input group-->
				<div class="position-relative w-md-400px me-md-2">
					<i class="ki-solid ki-magnifier fs-3 text-gray-500 position-absolute top-50 translate-middle ms-6"></i>
					<input type="text" class="form-control form-control-solid ps-10" placeholder="Search by Mobile, National Id Or Email..." asp-for="value" />
				</div>
				<!--end::Input group-->
				<!--begin:Action-->
				<div class="d-flex align-items-center">
					<button type="submit" class="btn btn-primary me-5">Search</button>
				</div>
				<!--end:Action-->
			</div>
			<!--end::Compact form-->
		</div>
		<!--end::Card body-->
	</div>
	<!--end::Card-->
</form>
<!--end::Form--> 
<div id="Result"></div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

Bookify.Web/Views/Subscribers/_Result.cshtml
@model SubscriberSearchResultViewModel

@if(Model is null)
{
    <div class="alert bg-light-warning border border-warning border-3 border-dashed d-flex flex-column flex-sm-row w-100 p-5">
        <!--begin::Icon-->
        <i class="ki-solid ki-notification-bing fs-2hx text-warning me-4 mb-5 mb-sm-0"></i>
        <!--end::Icon-->
        <!--begin::Content-->
        <div class="d-flex flex-column pe-0 pe-sm-10">
            <h5 class="mb-1">No subscribers has been found!</h5>
            <span>If you want to add new subscriber, <a asp-action="Create">click here.</a></span>
        </div>
        <!--end::Content-->
    </div>
}
else
{
	<!--begin::Row-->
	<div class="row">
		<!--begin::Col-->
		<div class="col-md-6 col-xxl-4">
			<!--begin::Card-->
			<div class="card">
				<!--begin::Card body-->
				<div class="card-body d-flex p-9">
					<!--begin::Avatar-->
					<div class="symbol symbol-65px symbol-circle me-5">
						<img src="@Model.ImageThumbnailUrl" alt="image" />
					</div>
					<!--end::Avatar-->
					<div class="d-flex flex-column justify-content-center">
						<!--begin::Name-->
						<a asp-action="Details" asp-route-id="@Model.Key" class="fs-4 text-gray-800 text-hover-primary fw-bold mb-0">@Model.FullName</a>
						<!--end::Name-->
						<!--begin::Position-->
						<div class="fw-semibold text-gray-500">@Model.Email</div>
						<!--end::Position-->
					</div>
					<div class="d-flex align-items-center" style="margin-left: auto;">
						<a asp-action="Details" asp-route-id="@Model.Key" class="btn btn-sm btn-primary">
							View
						</a>
					</div>
				</div>
				<!--end::Card body-->
			</div>
			<!--end::Card-->
		</div>
		<!--end::Col-->
	</div>
	<!--end::Row-->
}

Bookify.Web/Views/Subscribers/_SubscriptionRow.cshtml
@model SubscriptionViewModel

<tr>
    <td class="ps-4">@Model.StartDate.ToString("d MMM, yyyy")</td>
    <td>@Model.EndDate.ToString("d MMM, yyyy")</td>
    <td>
        <span class="badge badge-light-@(Model.Status == Statuses.Expired ? "danger" : Model.Status == Statuses.Active ? "success" : "warning" ) fs-7 fw-bold">@Model.Status</span>
    </td>
    <td>@Model.CreatedOn.ToString("d MMM, yyyy")</td>
</tr>